### ISSUE TITLE
MLproject file specification

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/mlflow-original#30]
This issue tracks the inclusion of using a `MLproject` file with R projects in the documentation.

Currently, users can have the following `MLproject` file in a directory, say `proj_dir`

```
name: My Project

entry_points:
  main:
    parameters:
      num_trees: {type: float, default: 25}
    command: "Rscript -e \"mlflow::mlflow_source('script1.R')\" --args --num_trees={num_trees}"
```

then invoke the command `mlflow run proj_dir`.

**Comment by kevinykuo** [comment]
As of https://github.com/rstudio/mlflow/commit/1491d1b0969bd8508ae5c59133c9bcf93fe9f9ff we can now have

```
name: My Project

entry_points:
  main:
    parameters:
      num_trees: {type: float, default: 25}
    command: "Rscript -e 'mlflow::mlflow_source(script1.R)' --args --num_trees={num_trees}"
```

which saves the user from escaping quotes.
